# Generated by Django 4.2 on 2023-05-20 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_pno_isdoctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pno',
            name='isDoctor',
        ),
    ]
