# Generated by Django 4.2 on 2023-05-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_pno_isdoctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='pno',
            name='isDoctor',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
