# Generated by Django 4.2 on 2023-05-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_pno_isdoctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pno',
            name='isDoctor',
            field=models.BigIntegerField(),
        ),
    ]
